services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - /root/volumes/audiobookshelf/audiobooks:/audiobooks
      - /root/volumes/audiobookshelf/podcasts:/podcasts
      - /root/volumes/audiobookshelf/config:/config
      - /root/volumes/audiobookshelf/metadata:/metadata
    environment:
      - TZ=Europe/Rome
    depends_on:
      - cloudflare-tunnel
    networks:
      - cloudflare-audiobookshelf

  cloudflare-tunnel:
    image: docker.io/cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - "TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}"
    networks:
      - cloudflare-audiobookshelf

networks:
  cloudflare-audiobookshelf: