services:
  portainer_agent:
    image: portainer/agent:2.21.3
    container_name: portainer_agent-1
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
