services:
  stump:
    image: aaronleopold/stump:latest
    container_name: stump-1
    restart: unless-stopped
    volumes:
      - config:/config
      - /mnt/NAS/Fumetti:/fumetti:ro
    ports:
      - 10801:10801
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - default_network

volumes:
  config:
    
networks:
  default_network:
    driver: bridge
