services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr-1
    restart: unless-stopped
    #ports:
    #  - "7575:7575"  # Expose the web interface
    volumes:
      - appdata:/app/data
      - configs:/app/data/configs
      - data:/data
    networks:
      - shared_network

volumes:
  appdata:
  configs:
  data:

networks:
  shared_network:
    external: true
    
