services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr-1
    restart: unless-stopped
    #ports:
    #  - "7575:7575"  # Expose the web interface
    volumes:
      - data:/app/data  # Persist Homarr data
    networks:
      - shared_network

volumes:
  data:  # Volume for Homarr data

networks:
  shared_network:
    external: true
    
