services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett-1
    restart: unless-stopped
    #ports:
    #  - 9117:9117
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - config:/config
    networks:
      - shared_network
    
networks:
  shared_network:
    external: true

volumes:
  config:
