services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager-1
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - shared_network
#default user: admin@example.com
#default password: changeme
volumes:
  data:
  letsencrypt:
  
networks:
  shared_network:
    external: true
        
