services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-1
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      - /root/compose_files:/data/compose  # Mount host directory for YAML files
    networks:
      - shared_network

volumes:
  data:

networks:
  shared_network:  
    name: shared_network
